"""
List of random words
"""

characters = ['tidy', 'romantic', 'meal',
              'man', 'mourn', 'possible',
              'punch', 'miniature', 'bizarre',
              'trust', 'fly', 'first', 'year',
              'chivalrous', 'cherry', 'abandoned',
              'brawny', 'rough', 'crow', 'weight',
              'wave', 'approval', 'quick', 'doctor',
              'sweet', 'unkempt', 'gusty', 'rampant',
              'knee', 'greet', 'fertile', 'thick',
              'argue', 'addicted', 'sea', 'acid', 'meddle',
              'cart', 'analyze', 'paste', 'flashy', 'fascinated',
              'fork', 'enormous', 'organic', 'battle', 'obscene',
              'bore', 'cooperative', 'nervous', 'fretful', 'believe',
              'mature', 'shade', 'argument', 'power', 'add',
              'prevent', 'writer', 'handle', 'damp', 'box', 'serve',
              'helpless', 'trashy', 'present', 'comb', 'lowly',
              'unaccountable', 'tame', 'judge', 'hair', 'tank', 'fact',
              'visitor', 'sleet', 'deer', 'voice', 'stove', 'son',
              'sturdy', 'camera', 'steady', 'dress', 'deep', 'ducks',
              'vanish', 'sad', 'passenger', 'null', 'repulsive', 'pale',
              'weather', 'tiresome', 'difficult', 'comparsion', 'raise',
              'eyes', 'robin', 'wanting', 'fantastic', 'little', 'sail',
              'conscious', 'nose', 'calendar', 'arm', 'receive', 'elderly',
              'guitar', 'visit', 'knife', 'grumpy', 'wrestle', 'disarm',
              'invention', 'share', 'connection', 'merciful', 'scribble',
              'throne', 'troubled', 'sign', 'snake', 'unknown', 'system',
              'festive', 'resolute', 'skip', 'cheer', 'brown', 'blushing',
              'bleach', 'minute', 'needle', 'different', 'tempt', 'basketball',
              'purpose', 'yellow', 'relax', 'red', 'blue', 'green', 'black']
